# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
# title can include HTML code.
title: SwiftGG # 网站标题
subtitle: 走心的 Swift 翻译组 # 网站副标题
description: SwiftGG翻译组，做高质量的Swift文章翻译，为你带来优质的国外Swift语言教程 # 网站描述，给搜索引擎用的，在生成html中的head->meta中可看到
author: SwiftGG # 网站作者
language: zh-CN # 语言
timezone:

# custom Site settings
SEOTitle: SwiftGG
keyword: "swift, swiftGG, SwiftGG, Swift, iOS" # seo key words

favicon: /img/logo_swiftgg.png # your favicon png
# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://swift.gg
root: /
# :year/:month/:day/:title/
permalink: :year/:month/:day/:title/ # 文章的永久链接格式
permalink_defaults:

# ---------------------------------------------------------------
# Hexo official settings
# ---------------------------------------------------------------
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing: Defined by Hexo
new_post_name: :title.md # File name of new posts
default_layout: post # 默认layout方式
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
auto_spacing: false # 在中文和英文之间加入空格
filename_case: 0
render_drafts: false # 显示草稿
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

archive_generator:
  per_page: 20
  yearly: true
  montyly: true

## Themes: https://hexo.io/themes/
theme: amber

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
  repo:
  branch:

# Basic config
## Menu
menu:
  Home: /
  Archives: /archives
  Tags: /related?tag=all
  Docs: /docs/index
  Events: /events/index
  Podcast: /podcast/index
  Code T: /codeT/index
  Media: /media/index
  About: /abount/index
  # Custom Menu
  # example:
  #   [O]  About: /about/index  (directory based)
  #   [O]  About: /about        (single .md file)

# Slider
slider: 10 # unit: seconds. `true` or number for enable and `false` for disable

# Topic
topic: false # tag array for enable and `false` for disable
# example:
#   [0] - essay
#       - note
#   [x] - false
#   [x] true

## RSS Feed
## docs: https://github.com/hexojs/hexo-generator-feed
rss:
  enable: false
  # path: # path to atom.xml or rss.xml

## Social links
social:
  # facebook: ...
  # github: ...
  # twitter: ...
  # weibo: ...
  websites:
    # - text: ...
    #   link: ...

## Sidebar
sidebar:
  leaf: To descript your blog. *Markdown* supported.
  github: Mitscherlich

## comments
### gitalk docs: https://github.com/gitalk/gitalk
### gitment docs: https://github.com/imsun/gitment
### valine docs: https://github.com/xCss/Valine
comments:
  enable: true
  engine: gitalk  # NOTE: you can ONLY use ONE comment system!
  gitalk:
    # required: github application client id
    clientID: process.env.clientId
    # required: github application client secret
    clientSecret: process.env.clientSecret
    repo: process.env.repo    # required: github repo
    owner: process.env.author # required: github repo owner
    admin:
      - process.env.author  # required: gitHub repo owner and collaborators
                            # only these guys can initialize github issues
  gitment:
    repo: process.env.repo    # required: github repo
    owner: process.env.author # required: github repo owner
    oauth:
      # required: github application client id
      client_id: process.env.clientId
      # required: github application client secret
      client_secret: process.env.clientSecret
  valine:
    # required: leancloud app id
    appId: process.env.appId
    # required: leancloud app key
    appKey: process.env.appKey

## Build-in Search
## NOTE: DONNT USE NOW!!! -- TOO BUGGY
# search:
#   enable: false
#   engine: build-in  # only support build-in currently
#   max: 5            # the number of suggestions

## powered by information
powered_by:
  author: Mitscherlich
  link: https://github.com/Mitscherlich

# External
## Google Analytics
google_analytics:
  enable: false
  track_id:  # replace to your track_id. It starts with 'UA-'.
